#include "theme.h"
#include "constants.h"
#include "settings.h"

#include <QApplication>
#include <QWidget>

namespace Theme {

namespace {
bool g_light = false;
std::vector<ChangeHandler> g_handlers;
}

void init() {
    g_light = AppSettings::instance().get("Appearance/theme", "dark").toString()
              == QLatin1String("light");
}

bool light() { return g_light; }

void addChangeHandler(ChangeHandler h) {
    g_handlers.push_back(std::move(h));
}

void notifyChanged() {
    for (const auto& h : g_handlers) h();
}

void applyLive() {
    init();                                   // 重读双档标志
    notifyChanged();                          // 重灌内联样式/缓存色(全量即时)
    if (QApplication* app = qobject_cast<QApplication*>(QApplication::instance()))
        app->setStyleSheet(appQss());         // 全局样式表即时切换
    for (QWidget* w : QApplication::topLevelWidgets())
        w->update();                          // 触发全窗口重绘刷新 T() 取色
}

QString appQss() {
    // 占位符按 %1..%39 顺序逐个 .arg:单个 arg() 每次替换最小编号占位符,
    // 取值全是 #hex,不含 %N 字样,链式安全
    return QStringLiteral(
        "QWidget {"
        "  font-family: \"Microsoft YaHei\", \"Segoe UI\", sans-serif;"
        "  font-size: 12px; color: %1; background: %2;"
        "}"
        "QMenu {"
        "  background: %3; color: %1;"
        "  border: 1px solid %4; border-radius: 6px; padding: 5px;"
        "}"
        "QMenu::item { padding: 6px 28px; border-radius: 4px; }"
        "QMenu::item:selected { background: %5; color: #FFF; }"
        "QMenu::separator { height: 1px; background: %4; margin: 4px 8px; }"
        // ── 菜单勾选指示器(2026-09-04 用户令:先要"能看出可勾";随后 #246 再令:
        // 小一点、直角、更扁平)──原生 windowsvista 的对勾在深色菜单上几乎隐形;
        // 未勾=直角细描边空框(预告可勾),勾中=主题色纯色方块+白对勾,无描边无圆角
        // (扁平=没有任何立体/包边装饰)。image 用编译进 qrc 的 menu_check.png
        // (自有资产,不碰 assets/icons-48 的 XnView 图)。
        "QMenu::indicator { width: 13px; height: 13px; margin-left: 6px; }"
        "QMenu::indicator:unchecked {"
        "  border: 1px solid %11; border-radius: 0px; background: transparent;"
        "}"
        "QMenu::indicator:disabled { border: 1px solid %4; border-radius: 0px; }"
        "QMenu::indicator:checked {"
        "  background: %5; border: none;"
        "  image: url(:/menu_check.png);"
        "}"
        // ── 滚动条:轨道 + 滑块 + 两端箭头按钮(Windows/XnView 式) ──
        // margin 让出箭头按钮的位置,sub-line/add-line 用 subcontrol-origin:margin 落进去
        "QScrollBar:vertical {"
        "  background: %6; width: 15px; border: none;"
        "  margin: 16px 0px 16px 0px;"
        "}"
        "QScrollBar::handle:vertical {"
        "  background: %7; border-radius: 3px; min-height: 24px;"
        "  margin: 0px 2px 0px 2px;"
        "}"
        "QScrollBar::handle:vertical:hover { background: %8; }"
        "QScrollBar::add-line:vertical {"
        "  background: %9; border: none; height: 16px;"
        "  subcontrol-position: bottom; subcontrol-origin: margin;"
        "}"
        "QScrollBar::sub-line:vertical {"
        "  background: %9; border: none; height: 16px;"
        "  subcontrol-position: top; subcontrol-origin: margin;"
        "}"
        "QScrollBar::add-line:vertical:hover, QScrollBar::sub-line:vertical:hover {"
        "  background: %10;"
        "}"
        // 箭头 = 四条边里只留一条有颜色,其余透明 → 一个实心三角形
        "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {"
        "  background: none; width: 0; height: 0;"
        "  border-left: 4px solid transparent; border-right: 4px solid transparent;"
        "}"
        "QScrollBar::up-arrow:vertical { border-bottom: 6px solid %11; }"
        "QScrollBar::down-arrow:vertical { border-top: 6px solid %11; }"
        "QScrollBar:horizontal {"
        "  background: %6; height: 15px; border: none;"
        "  margin: 0px 16px 0px 16px;"
        "}"
        "QScrollBar::handle:horizontal {"
        "  background: %7; border-radius: 3px; min-width: 24px;"
        "  margin: 2px 0px 2px 0px;"
        "}"
        "QScrollBar::handle:horizontal:hover { background: %8; }"
        "QScrollBar::add-line:horizontal {"
        "  background: %9; border: none; width: 16px;"
        "  subcontrol-position: right; subcontrol-origin: margin;"
        "}"
        "QScrollBar::sub-line:horizontal {"
        "  background: %9; border: none; width: 16px;"
        "  subcontrol-position: left; subcontrol-origin: margin;"
        "}"
        "QScrollBar::add-line:horizontal:hover, QScrollBar::sub-line:horizontal:hover {"
        "  background: %10;"
        "}"
        "QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {"
        "  background: none; width: 0; height: 0;"
        "  border-top: 4px solid transparent; border-bottom: 4px solid transparent;"
        "}"
        "QScrollBar::left-arrow:horizontal { border-right: 6px solid %11; }"
        "QScrollBar::right-arrow:horizontal { border-left: 6px solid %11; }"
        "QScrollBar::add-page, QScrollBar::sub-page { background: transparent; }"
        "QSlider::groove:horizontal { height: 4px; background: %12; border-radius: 2px; }"
        "QSlider::handle:horizontal {"
        "  width: 13px; height: 13px; margin: -5px 0;"
        "  background: %5; border-radius: 7px;"
        "}"
        "QSlider::handle:horizontal:hover { background: #5B9BFF; }"
        "QToolTip {"
        "  background: %3; color: %1; font-size: 11px;"
        "  border: 1px solid %4; border-radius: 4px; padding: 5px 8px;"
        "}"
        "QLineEdit {"
        "  background: %13; color: %1;"
        "  border: 1px solid %12; border-radius: 5px; padding: 3px 9px;"
        "}"
        "QLineEdit:focus { border-color: %5; }"
        "QSplitter::handle { background: %4; }"
        "QSplitter::handle:horizontal { width: 1px; }"
        // ── 下拉框 / 数字框:箭头全应用统一 ─────────────────────────────
        // 只写 ::down-arrow 是不够的:样式表一旦存在,Qt 就要自己画 drop-down 那一块,
        // 而它**没有 background 时用的是调色板 Base**(深色主题下 = 一块白),
        // 三角被盖在里面 = 用户看到的"一个白色实心长方形按钮,没有下箭头"。
        // 这里显式给透明底 + 与滚动条/标签滚动按钮同款的边框三角(同一个 %11 箭头色),
        // 所有 QComboBox / QSpinBox / QDoubleSpinBox 一次性跟着改,不再各页各写一份。
        "QComboBox::drop-down {"
        "  width: 18px; border: none; background: transparent;"
        "  subcontrol-origin: padding; subcontrol-position: top right;"
        "}"
        "QComboBox::drop-down:hover { background: %16; }"
        "QComboBox::down-arrow {"
        "  image: none; width: 0; height: 0; background: none;"
        "  border-left: 4px solid transparent; border-right: 4px solid transparent;"
        "  border-top: 5px solid %11; margin-right: 6px;"
        "}"
        "QAbstractSpinBox::up-button, QAbstractSpinBox::down-button {"
        "  width: 14px; border: none; background: transparent;"
        "}"
        "QAbstractSpinBox::up-arrow, QAbstractSpinBox::down-arrow {"
        "  width: 0; height: 0; background: none;"
        "  border-left: 3px solid transparent; border-right: 3px solid transparent;"
        "}"
        "QAbstractSpinBox::up-arrow { border-bottom: 4px solid %11; }"
        "QAbstractSpinBox::down-arrow { border-top: 4px solid %11; }"
        // ── 查看器标签条 ──
        // 必须逐子控件写:上面那条 QWidget 规则只管底色+纯白文字,tabs 交给
        // windowsvista 自己画就是"浅灰 tab + 白字" = 一条读不出字的空白栏
        "QTabBar { background: %3; border: none; }"
        "QTabBar::tab {"
        "  background: %14; color: %1;"
        "  border: 1px solid %4; border-bottom: none;"
        "  border-top-left-radius: 5px; border-top-right-radius: 5px;"
        "  margin-top: 3px; padding: 4px 4px 4px 10px;"
        "  min-width: 72px; max-width: 190px;"
        "}"
        "QTabBar::tab:selected {"
        "  background: %15; margin-top: 2px;"
        "  border-top: 2px solid %5;"
        "}"
        "QTabBar::tab:hover:!selected { background: %16; }"
        // 标签溢出时的左右滚动按钮:箭头与滚动条同款(边框三角形),不自带图标
        "QTabBar::scroller { width: 32px; margin: 0; }"
        "QTabBar QToolButton { background: %9; border: none; }"
        "QTabBar QToolButton:hover { background: %10; }"
        "QTabBar QToolButton::left-arrow {"
        "  width: 0; height: 0; background: none;"
        "  border-top: 4px solid transparent; border-bottom: 4px solid transparent;"
        "  border-right: 6px solid %11;"
        "}"
        "QTabBar QToolButton::right-arrow {"
        "  width: 0; height: 0; background: none;"
        "  border-top: 4px solid transparent; border-bottom: 4px solid transparent;"
        "  border-left: 6px solid %11;"
        "}"
        // ── #89 样式收敛:原散在各控件构造期的静态内联 setStyleSheet 并入本表。
        // 语义与原内联表逐条一致,但级联从"控件表必赢"变为"同特异性靠位置",
        // 因此块内顺序敏感:工具条后代泛规则在前,#addrBar/#fmtFilterCombo/
        // 小箭头钮靠排在其后赢回自己的属性;后代泛规则刻意保留 QWidget 后代
        // 匹配(分隔线/弹层容器当年吃到的 background 原样复刻,防像素漂移)。
        "QWidget#addrRow, QWidget#toolRow,"
        "QWidget#addrRow QWidget, QWidget#toolRow QWidget {"
        "  background: %3; border-bottom: 1px solid %4;"
        "}"
        "QWidget#addrRow QToolButton, QWidget#toolRow QToolButton {"
        "  background: transparent; border: none; border-radius: 4px;"
        "  padding: 3px 6px; color: %1; font-size: 11px;"
        "}"
        "QWidget#addrRow QToolButton:hover, QWidget#toolRow QToolButton:hover {"
        "  background: %16;"
        "}"
        "QWidget#addrRow QToolButton::menu-indicator,"
        "QWidget#toolRow QToolButton::menu-indicator { image: none; }"
        "QToolButton#barArrowBtn { color: %11; font-size: 9px; }"
        "QLineEdit#addrBar {"
        "  background: %13; color: %1; border: 1px solid %12;"
        "  border-radius: 4px; padding: 2px 8px; font-size: 11px;"
        "}"
        "QLabel#fmtComboArrow { color: %11; background: transparent; font-size: 9px; }"
        "QWidget#paneHdr, QWidget#paneHdr QWidget {"
        "  background: %20; border-bottom: 1px solid %4;"
        "}"
        "QWidget#paneHdr QLabel {"
        "  background: transparent; color: %1; font-size: 12px;"
        "}"
        "QWidget#paneHdr QToolButton {"
        "  background: transparent; border: none; border-radius: 4px;"
        "  color: %1; font-size: 13px;"
        "}"
        "QWidget#paneHdr QToolButton:hover { background: %16; }"
        "QWidget#treePane, QWidget#favPane, QWidget#filterPane {"
        "  background: %14; border: none;"
        "}"
        "QWidget#previewPane, QWidget#infoPane {"
        "  background: %15; border: none;"
        "}"
        "QStatusBar {"
        "  background: %21; border-top: 1px solid %4;"
        "  color: %1; font-size: 11px; padding: 2px 10px;"
        "}"
        "QStatusBar::item { border: none; }"
        "QLabel#statusLabel, QLabel#pathLabel { color: %1; background: transparent; }"
        "QMenuBar {"
        "  background: %19; color: %1; font-size: 12px;"
        "  padding: 3px 2px; border-bottom: 1px solid %4;"
        "}"
        "QMenuBar::item { background: transparent; padding: 4px 10px; border-radius: 3px; }"
        "QMenuBar::item:selected { background: %16; }"
        "QMenuBar::item:pressed { background: %5; color: #FFF; }"
        "QToolButton#tabCloseBtn {"
        "  border: none; background: transparent; color: %22;"
        "  font-size: 14px; padding: 0 2px;"
        "}"
        "QToolButton#tabCloseBtn:hover { color: %1; background: %16; border-radius: 3px; }"
        "QToolButton#filmNavBtn {"
        "  background: rgba(24,24,30,215); border: 1px solid #3A3A42;"
        "  border-radius: 10px;"
        "}"
        "QToolButton#filmNavBtn:hover { background: #3A3A42; border-color: #6A6A74; }"
        "QLabel#filmDragHint {"
        "  background: rgba(24,24,30,235); color: #FFFFFF;"
        "  border: 1px solid #3A3A42; border-radius: 4px;"
        "  padding: 3px 8px; font-size: 12px;"
        "}"
        "QFrame#toolSep { color: %24; }"
        "QComboBox#fmtFilterCombo {"
        "  background: %3; color: %1; border: 1px solid %4;"
        "  border-radius: 4px; padding: 2px 10px; font-size: 12px; min-height: 22px;"
        "}"
        "QComboBox#fmtFilterCombo:hover { border-color: %23; }"
        "QComboBox#fmtFilterCombo:focus { border-color: %5; }"
        "QComboBox#fmtFilterCombo::drop-down {"
        "  width: 18px; border: none; background: transparent;"
        "  subcontrol-origin: padding; subcontrol-position: top right;"
        "}"
        "QComboBox#fmtFilterCombo::down-arrow {"
        "  image: none; width: 0; height: 0; background: none; border: none;"
        "}"
        "QComboBox#fmtFilterCombo QAbstractItemView {"
        "  background: %13; color: %1; border: 1px solid %4;"
        "  selection-background-color: %5; outline: none;"
        "}"
        "QComboBox#fmtFilterCombo QAbstractItemView::item {"
        "  min-height: 24px; padding: 2px 8px;"
        "}"
        // ── 对话框按钮(2026-09-03 用户令:确定/取消不够醒目,边框与背景融为一体)──
        // 全部对话框统一成「次按钮=底色+蓝色描边,默认按钮=蓝底白字」,
        // 与设置对话框既有按钮样式同口径(那里是内联写死的,这里是全局兜底)。
        // 必须放在 QMessageBox 之前:两条规则特异性相同,后者赢 —— 消息框
        // 仍是它自己的老样式。
        "QDialog QPushButton {"
        "  background: %16; color: %1;"
        "  border: 1px solid %5; padding: 6px 18px; border-radius: 4px;"
        "}"
        "QDialog QPushButton:hover { background: %17; }"
        "QDialog QPushButton:default {"
        "  background: %5; border-color: %5; color: #FFF;"
        "}"
        "QDialog QPushButton:default:hover { background: %18; }"
        "QMessageBox { background: %2; color: %1; }"
        "QMessageBox QLabel { color: %1; background: transparent; }"
        "QMessageBox QPushButton {"
        "  background: %16; color: %1;"
        "  border: 1px solid %12; padding: 6px 18px; border-radius: 4px;"
        "}"
        "QMessageBox QPushButton:hover {"
        "  background: %17; border-color: %5;"
        "}"
        // ── #89 收敛(批3):views 层静态样式(文件网格/查找条/重命名框/排序表头/
        // 全屏胶片条/文件卡片)。类型选择器用自定义类名(FileGrid/FileCanvas/
        // SortHeader/FileCard),普通容器靠 objectName。全屏胶片条与 LIVE 徽章
        // 沿用原内联的硬编码深色(浮层,不随主题换档)。
        "FileGrid { background: %13; border: none; }"
        "FileCanvas { background: %13; }"
        "QWidget#findBar {"
        "  background: %3; border: 1px solid %4; border-radius: 4px;"
        "}"
        "QWidget#findBar QLineEdit {"
        "  background: %13; color: %1; border: 1px solid %4;"
        "  border-radius: 3px; padding: 1px 6px; selection-background-color: %5;"
        "}"
        "QWidget#findBar QToolButton {"
        "  background: transparent; border: none; border-radius: 3px;"
        "}"
        "QWidget#findBar QToolButton:hover { background: %16; }"
        "QWidget#findBar QToolButton:pressed { background: %4; }"
        "QWidget#findBar QToolButton:disabled { background: transparent; }"
        "QLabel#findInfo {"
        "  color: %25; font-size: 12px; background: transparent; border: none;"
        "}"
        "QLineEdit#renameEdit {"
        "  background: %13; color: %1; border: 1px solid %5;"
        "  font-size: 12px; padding: 0 2px;"
        "}"
        // 排序表头:原内联是裸声明(背景+下边线泼给全部子孙,含列钮与垫片),
        // 这里用 QWidget 后代选择器原样复刻,列钮规则紧随其后靠排位赢回透明底
        "SortHeader, SortHeader QWidget {"
        "  background: %3; border-bottom: 1px solid %4;"
        "}"
        "SortHeader QPushButton {"
        "  background: transparent; color: %1; border: none;"
        "  padding: 2px 8px; font-size: 11px; text-align: left; border-radius: 4px;"
        "}"
        "SortHeader QPushButton:hover { color: %1; background: %16; }"
        // 全屏胶片条:浮层,原内联硬编码深色,不随主题
        "QWidget#filmStrip {"
        "  background: rgba(18,18,24,235); border: 1px solid #3A3A42; border-radius: 8px;"
        "}"
        "QWidget#filmStrip::viewport { background: transparent; }"
        "QWidget#filmBtnBar QToolButton {"
        "  background: transparent; border: none; border-radius: 4px;"
        "  padding: 2px 6px; font-size: 11px; color: #9A9AA4;"
        "}"
        "QWidget#filmBtnBar QToolButton:hover { background: #3A3A42; color: #FFFFFF; }"
        "QWidget#filmBtnBar QToolButton:checked {"
        "  background: rgba(0,120,215,80); color: #FFFFFF;"
        "}"
        "QWidget#filmBtnBar QToolButton#filmClose { padding: 0; }"
        "QLabel#filmCaption {"
        "  background: transparent; color: #FFFFFF; font-size: 13px; font-weight: 600;"
        "}"
        // 文件卡片:本体透明(图片之外纯黑由卡片父级透出)
        "FileCard { background: transparent; border: none; }"
        "QLabel#cardThumb { background: transparent; }"
        "QLabel#cardLiveBadge {"
        "  background: rgba(0,0,0,150); color: #FFF; font-size: 9px; font-weight: bold;"
        "  padding: 2px 7px; border-radius: 8px; border: 1px solid rgba(255,255,255,60);"
        "}"
        // ── #89 收敛(批4):预览面板静态表面。控件上的动态样式(图片边框态、
        // 评级点、CMYK 勾选后切换解码等)仍留控件级。播放控制栏/全屏浮动条/PDF 条
        // 原内联是裸声明(底色边框泼给全部子孙),此处用 QWidget 后代选择器
        // 原样复刻,按钮规则紧随其后靠排位赢回透明底。
        "QLabel#pvPlaceholder { color: %26; font-size: 13px; background: transparent; }"
        "QLabel#pvAudio { color: %25; font-size: 16px; background: transparent; }"
        "QLabel#pvWave { color: %26; font-size: 12px; background: transparent; }"
        "QLabel#pvRawCaption { color: %26; font-size: 13px; background: transparent; }"
        "QPushButton#pvRawBtn {"
        "  background: %5; color: #FFF; border: none; border-radius: 6px;"
        "  padding: 6px 14px; font-size: 12px;"
        "}"
        "QPushButton#pvRawBtn:hover { background: %18; }"
        "QPushButton#pvRawBtn:disabled {"
        "  background: %27; border: 1px solid %4; color: %28;"
        "}"
        "QPushButton#pvCmykBtn {"
        "  background: %28; color: #FFF; border: none; border-radius: 6px;"
        "  padding: 4px 10px; font-size: 11px;"
        "}"
        "QPushButton#pvCmykBtn:hover { background: %5; }"
        "QPushButton#pvCmykBtn:checked { background: %18; }"
        "QTextEdit#pvText {"
        "  background: %13; color: %1; border: none;"
        "  font-family: 'Consolas','Courier New',monospace; font-size: 13px;"
        "  selection-background-color: %5;"
        "}"
        // 视频区底:深色恒近黑;浅色主题下用户令"预览视频背景应为白色"。
        // (视频面本体另有调色板,见 applyVideoBackdrop;这里管控件露出的边角)
        "QWidget#pvVideo { background: %40; }"
        "QWidget#pvControlBar, QWidget#pvControlBar QWidget {"
        "  background: %3; border-top: 1px solid %4;"
        "}"
        "QWidget#pvControlBar QPushButton, QWidget#pvControlBar QToolButton {"
        "  background: transparent; border: none; border-radius: 4px; padding: 4px;"
        "}"
        "QWidget#pvControlBar QPushButton:hover,"
        "QWidget#pvControlBar QToolButton:hover { background: %16; }"
        "QSlider#pvProgress::groove:horizontal"
        "{ height: 3px; background: %4; border-radius: 1px; }"
        "QSlider#pvProgress::sub-page:horizontal { background: %5; border-radius: 1px; }"
        "QSlider#pvProgress::add-page:horizontal { background: %4; border-radius: 1px; }"
        "QSlider#pvProgress::handle:horizontal {"
        "  width: 9px; height: 9px; margin: -3px 0; background: %1; border-radius: 4px;"
        "}"
        "QSlider#pvProgress::handle:horizontal:hover { background: #DCE7FF; }"
        "QLabel#pvTime { color: %1; font-size: 12px; background: transparent; }"
        "QLabel#pvLiveBadge {"
        "  background: rgba(0,0,0,150); color: #FFF; border-radius: 8px;"
        "  padding: 2px 10px; font-size: 11px; font-weight: bold;"
        "  border: 1px solid rgba(255,255,255,60);"
        "}"
        "QLabel#pvVolVal { background: transparent; color: %1; font-size: 13px; }"
        "QScrollBar#pvOverlaySb { background: rgba(20,20,24,200); border: none; margin: 0; }"
        "QScrollBar#pvOverlaySb::handle { background: #5A5A62; border-radius: 3px; }"
        "QScrollBar#pvOverlaySb::handle:hover { background: #7A7A82; }"
        "QScrollBar#pvOverlaySb::add-line, QScrollBar#pvOverlaySb::sub-line"
        "{ height: 0; width: 0; }"
        "QWidget#pvFloatBar, QWidget#pvFloatBar QWidget {"
        "  background: rgba(18,18,22,225); border: 1px solid #3A3A42; border-radius: 6px;"
        "}"
        "QWidget#pvFloatBar QPushButton {"
        "  background: transparent; border: none; border-radius: 4px;"
        "  padding: 3px; color: #E8E8E8; min-width: 26px;"
        "}"
        "QWidget#pvFloatBar QPushButton:hover { background: #3A3A42; }"
        // 平移导航小窗:必须 ID 选择器只匹配自身(#111 的账:子控件吃到 1px
        // 边框会让缩略图 pixmap 画进内容矩形,蓝框对不上位)
        "QWidget#panNavTool { background: rgba(14,14,18,220); border: 1px solid #3A3A42; }"
        "QWidget#pvPanView { background: transparent; border: 1px solid #4C9AF5; }"
        "QWidget#pvPdfBar, QWidget#pvPdfBar QWidget {"
        "  background: rgba(18,18,22,225); border: 1px solid #3A3A42; border-radius: 6px;"
        "}"
        "QWidget#pvPdfBar QPushButton {"
        "  background: transparent; border: none; border-radius: 4px;"
        "  padding: 2px 4px; color: #E8E8E8; min-width: 24px;"
        "}"
        "QWidget#pvPdfBar QPushButton:hover { background: #3A3A42; }"
        "QWidget#pvPdfBar QPushButton:disabled { color: #5A5A62; }"
        "QLabel#pvPdfLabel {"
        "  background: transparent; color: #E0E0E0; font-size: 12px; padding: 0 4px;"
        "}"
        // ── #89 收敛(批5):对话框与辅助面板静态表面。四个对话框的整表迁入时
        // 统一加 QDialog#对象名 前缀:原"控件自有表压过应用表"的就近语义由
        // 特异性 a=1 复刻。设置页 group() 容器的裸声明 background:transparent
        // 会就近压过对话框表 —— 组内输入框/按钮/下拉框现状即透明底,复刻规则
        // 必须放在设置对话框块之后(同特异性靠排位赢),且只还原背景,
        // 描边/内距/字色仍由对话框块按属性合并提供。
        "QDialog#searchDialog { background: %2; }"
        "QDialog#searchDialog QLabel { color: %1; background: transparent; }"
        "QDialog#searchDialog QLineEdit {"
        "  background: %13; color: %1; border: 1px solid %4;"
        "  border-radius: 3px; padding: 5px 8px;"
        "}"
        "QDialog#searchDialog QPushButton {"
        "  background: %3; color: %1; border: 1px solid %4;"
        "  border-radius: 3px; padding: 6px 18px;"
        "}"
        "QDialog#searchDialog QPushButton:hover { border-color: %5; }"
        "QDialog#searchDialog QPushButton:disabled { color: %26; }"
        "QDialog#searchDialog QCheckBox {"
        "  color: %1; background: transparent; spacing: 6px;"
        "}"
        "QDialog#searchDialog QTreeWidget {"
        "  background: %13; color: %1; border: 1px solid %4; outline: none;"
        "}"
        "QDialog#searchDialog QTreeWidget::item { padding: 3px 2px; }"
        "QDialog#searchDialog QTreeWidget::item:selected { background: %5; }"
        "QDialog#searchDialog QHeaderView::section {"
        "  background: %3; color: %1; border: 1px solid %4; padding: 4px 6px;"
        "}"
        "QDialog#searchDialog QLabel#searchStatus { color: %28; }"
        "QDialog#imgSearchDialog { background: %2; }"
        "QDialog#imgSearchDialog QLabel { color: %1; background: transparent; }"
        "QDialog#imgSearchDialog QLineEdit {"
        "  background: %13; color: %1; border: 1px solid %4;"
        "  border-radius: 3px; padding: 6px 10px;"
        "}"
        "QDialog#imgSearchDialog QComboBox {"
        "  background: %13; color: %1; border: 1px solid %4;"
        "  border-radius: 3px; padding: 5px 8px;"
        "}"
        "QDialog#imgSearchDialog QComboBox::drop-down {"
        "  width: 16px; border: none; background: transparent;"
        "  subcontrol-origin: padding; subcontrol-position: top right;"
        "}"
        "QDialog#imgSearchDialog QComboBox::down-arrow {"
        "  image: none; width: 0; height: 0; background: none;"
        "  border-left: 4px solid transparent; border-right: 4px solid transparent;"
        "  border-top: 5px solid %11; margin-right: 6px;"
        "}"
        "QDialog#imgSearchDialog QComboBox QAbstractItemView {"
        "  background: %13; color: %1; selection-background-color: %5;"
        "}"
        "QDialog#imgSearchDialog QPushButton {"
        "  background: %3; color: %1; border: 1px solid %4;"
        "  border-radius: 3px; padding: 6px 20px;"
        "}"
        "QDialog#imgSearchDialog QPushButton:hover { border-color: %5; }"
        "QDialog#imgSearchDialog QPushButton:disabled { color: %28; }"
        "QDialog#imgSearchDialog QListWidget {"
        "  background: %13; color: %1; border: 1px solid %4; outline: none;"
        "}"
        "QDialog#imgSearchDialog QListWidget::item { padding: 2px; }"
        "QDialog#imgSearchDialog QListWidget::item:selected { background: %5; }"
        "QDialog#imgSearchDialog QLabel#imgSearchStatus { color: %28; }"
        "QDialog#dbMaintDialog { background: %13; }"
        "QDialog#dbMaintDialog QLabel { color: %1; background: transparent; }"
        "QDialog#dbMaintDialog QTableWidget {"
        "  background: %13; color: %1; border: 1px solid %4;"
        "}"
        "QDialog#dbMaintDialog QHeaderView::section {"
        "  background: %13; color: %1; border: none; padding: 4px;"
        "}"
        "QDialog#dbMaintDialog QPushButton {"
        "  background: %3; color: %1; border: 1px solid %4;"
        "  padding: 5px 14px; border-radius: 4px;"
        "}"
        "QDialog#dbMaintDialog QPushButton:hover { border-color: %5; }"
        "QDialog#aboutDialog { background: %13; }"
        "QDialog#aboutDialog QLabel { color: %1; background: transparent; }"
        "QDialog#aboutDialog QFrame {"
        "  background: %4; max-height: 1px; border: none;"
        "}"
        "QDialog#aboutDialog QPushButton {"
        "  background: %3; color: %1; border: 1px solid %4;"
        "  padding: 5px 18px; border-radius: 4px;"
        "}"
        "QDialog#aboutDialog QPushButton:hover { border-color: %5; }"
        "QDialog#settingsDialog { background: %2; }"
        "QDialog#settingsDialog QTreeWidget {"
        "  background: %13; color: %1; border: none; outline: none;"
        "}"
        "QDialog#settingsDialog QTreeWidget::item"
        "{ height: 26px; padding: 0 8px; border: none; }"
        "QDialog#settingsDialog QTreeWidget::item:hover"
        "{ background: %16; border: none; }"
        "QDialog#settingsDialog QTreeWidget::item:selected"
        "{ background: %5; color: %1; border: none; }"
        "QDialog#settingsDialog QLineEdit {"
        "  background: %13; color: %1; border: 1px solid %4;"
        "  border-radius: 3px; padding: 4px 8px;"
        "}"
        "QDialog#settingsDialog QLineEdit[readOnly=\"true\"]"
        "{ color: %26; background: %13; }"
        "QDialog#settingsDialog QLabel { color: %1; background: transparent; }"
        "QDialog#settingsDialog QCheckBox {"
        "  color: %1; background: transparent; spacing: 6px;"
        "}"
        "QDialog#settingsDialog QComboBox {"
        "  background: %13; color: %1; border: 1px solid %4;"
        "  border-radius: 3px; padding: 3px 8px; min-width: 180px;"
        "}"
        "QDialog#settingsDialog QComboBox::drop-down {"
        "  width: 16px; border: none; background: transparent;"
        "  subcontrol-origin: padding; subcontrol-position: top right;"
        "}"
        "QDialog#settingsDialog QComboBox::down-arrow {"
        "  image: none; width: 0; height: 0; background: none;"
        "  border-left: 4px solid transparent; border-right: 4px solid transparent;"
        "  border-top: 5px solid %11; margin-right: 6px;"
        "}"
        "QDialog#settingsDialog QComboBox QAbstractItemView {"
        "  background: %13; color: %1; selection-background-color: %5;"
        "}"
        "QDialog#settingsDialog QSpinBox {"
        "  background: %13; color: %1; border: 1px solid %4;"
        "  border-radius: 3px; padding: 3px 6px;"
        "}"
        "QDialog#settingsDialog QSpinBox::up-button,"
        "QDialog#settingsDialog QSpinBox::down-button"
        "{ width: 14px; border: none; background: transparent; }"
        "QDialog#settingsDialog QSpinBox::up-arrow {"
        "  image: none; width: 0; height: 0; background: none;"
        "  border-left: 3px solid transparent; border-right: 3px solid transparent;"
        "  border-bottom: 4px solid %11;"
        "}"
        "QDialog#settingsDialog QSpinBox::down-arrow {"
        "  image: none; width: 0; height: 0; background: none;"
        "  border-left: 3px solid transparent; border-right: 3px solid transparent;"
        "  border-top: 4px solid %11;"
        "}"
        "QDialog#settingsDialog QPushButton {"
        "  background: %3; color: %1; border: 1px solid %4;"
        "  border-radius: 3px; padding: 5px 16px;"
        "}"
        "QDialog#settingsDialog QPushButton:hover { border-color: %5; }"
        "QDialog#settingsDialog QGroupBox {"
        "  color: %1; font-weight: 700; border: 1px solid %4;"
        "  border-radius: 5px; margin-top: 12px; padding: 14px 10px 10px 10px;"
        "  background: %2;"
        "}"
        "QDialog#settingsDialog QGroupBox::title"
        "{ subcontrol-origin: margin; left: 12px; top: 2px; }"
        "QDialog#settingsDialog QScrollArea { background: %2; border: none; }"
        "QDialog#settingsDialog QToolButton {"
        "  background: %3; color: %1; border: 1px solid %4;"
        "  border-radius: 3px; padding: 3px 10px;"
        "}"
        "QDialog#settingsDialog QToolButton:hover { border-color: %5; }"
        // 快捷键/维护两页的表格(对象名 settingsTable):此前没有任何规则,
        // 表头被原生风格画成浅底,叠加全局白字 → 白底白字不可读(#18)
        "QDialog#settingsDialog QTableWidget {"
        "  background: %13; color: %1; border: 1px solid %4; outline: none;"
        "  gridline-color: %4;"
        "}"
        "QDialog#settingsDialog QTableWidget::item"
        "{ padding: 2px 6px; selection-background-color: %5; }"
        "QDialog#settingsDialog QTableWidget::item:selected"
        "{ background: %5; color: #FFFFFF; }"
        "QDialog#settingsDialog QTableWidget QTableCornerButton::section"
        "{ background: %3; border: none; }"
        "QDialog#settingsDialog QTableWidget QHeaderView::section {"
        "  background: %3; color: %1; border: none;"
        "  border-right: 1px solid %4; border-bottom: 1px solid %4;"
        "  padding: 4px 6px; font-size: 12px;"
        "}"
        // 设置页内部 ID 精确规则(a=2 压过上面的类型规则);底部三钮原是
        // 每颗按钮各自灌的 btnQss,样式与对话框块不同口径(radius/内距)
        "QDialog#settingsDialog QPushButton#settingsStdBtn {"
        "  background: %3; color: %1; border: 1px solid %4;"
        "  padding: 6px 28px; border-radius: 4px;"
        "}"
        "QDialog#settingsDialog QPushButton#settingsStdBtn:hover { border-color: %5; }"
        "QDialog#settingsDialog QPushButton#okBtn {"
        "  background: %5; border-color: %5; color: #FFF;"
        "}"
        "QDialog#settingsDialog QPushButton#okBtn:hover { background: %18; }"
        "QDialog#settingsDialog QLabel#settingsPageTitle {"
        "  font-size: 15px; font-weight: 700; color: %1; background: transparent;"
        "}"
        "QDialog#settingsDialog QFrame#settingsPageRule"
        "{ background: %1; border: none; }"
        "QDialog#settingsDialog QLabel#settingsGroupTitle {"
        "  font-size: 12px; font-weight: 700; color: %29; background: transparent;"
        "}"
        "QDialog#settingsDialog QFrame#grpFrame {"
        "  background: %27; border: 1px solid %4; border-radius: 5px;"
        "}"
        "QDialog#settingsDialog QLabel#settingsDbSummary"
        "{ color: %32; background: transparent; }"
        "QDialog#settingsDialog QLabel#settingsNote"
        "{ background: transparent; color: %28; }"
        "QDialog#settingsDialog QLabel#settingsMouseTip {"
        "  color: %33; font-size: 12px; background: transparent;"
        "}"
        "QDialog#settingsDialog QListWidget#labelColorList {"
        "  background: %13; border: 1px solid %4; outline: none;"
        "}"
        "QDialog#settingsDialog QListWidget#labelColorList::item"
        "{ height: 24px; padding: 0 8px; border: none; }"
        "QDialog#settingsDialog QListWidget#labelColorList::item:selected"
        "{ background: %5; color: %1; border: none; }"
        "QDialog#settingsDialog QToolButton#labelWhiteSwatch"
        "{ background: #FFFFFF; border: 1px solid %4; }"
        // group() 裸声明 transparent 的就近压制复刻(见本块首注释):
        // 枚举组内控件类型而非 QWidget 通配,避免吃掉 grpFrame 的卡片底
        "QWidget#settingsGroup { background: transparent; }"
        "QWidget#settingsGroup QLineEdit, QWidget#settingsGroup QComboBox,"
        "QWidget#settingsGroup QSpinBox, QWidget#settingsGroup QPushButton,"
        "QWidget#settingsGroup QToolButton, QWidget#settingsGroup QRadioButton,"
        "QWidget#settingsGroup QKeySequenceEdit, QWidget#settingsGroup QListView"
        "{ background: transparent; }"
        // 分类筛选器面板(常驻 Dock,非对话框;2026-09-05 扁平化改版:
        // 两种模式切换钮 + 圆形色块,去掉描边小钮的琐碎感)
        "QWidget#filterPanel QToolButton#filterModeBtn {"
        "  background: transparent; color: %1; border: 1px solid %4;"
        "  border-radius: 4px; padding: 4px 8px; font-size: 12px; font-weight: normal;"
        "}"
        "QWidget#filterPanel QToolButton#filterModeBtn:hover { background: %16; }"
        "QWidget#filterPanel QToolButton#filterModeBtn:checked"
        "{ background: %16; border-color: %5; color: %1; }"
        "QWidget#filterPanel QPushButton {"
        "  background: transparent; color: %1; border: 1px solid %4;"
        "  border-radius: 4px; padding: 2px 8px; font-size: 12px;"
        "}"
        "QWidget#filterPanel QPushButton:hover { background: %16; }"
        "QWidget#filterPanel QCheckBox {"
        "  color: %1; font-size: 12px; spacing: 6px; background: transparent;"
        "}"
        "QWidget#filterPanel QCheckBox::indicator { width: 14px; height: 14px; }"
        "QWidget#filterPanel QComboBox {"
        "  background: transparent; color: %1; border: 1px solid %4;"
        "  border-radius: 4px; padding: 2px 4px; font-size: 12px;"
        "}"
        "QWidget#filterPanel QToolButton#filterColorBtn {"
        "  background: transparent; border: 2px solid transparent; border-radius: 14px;"
        "  padding: 0;"
        "}"
        "QWidget#filterPanel QToolButton#filterColorBtn:hover"
        "{ border-color: %11; }"
        "QWidget#filterPanel QToolButton#filterColorBtn:checked"
        "{ border: 2px solid %5; }"
        "QWidget#filterPanel QLabel#filterHitLabel"
        "{ color: %28; font-size: 11px; background: transparent; }"
        // 信息面板(直方图条+元数据树)与收藏夹列表:原 #248 重灌钩子的
        // 静态部分迁入后随 applyLive 自动跟上主题
        "QLabel#metaHistLabel { background: %15; border-bottom: 1px solid %34; }"
        "QTreeWidget#metaTree {"
        "  background: %13; color: %35; border: none; font-size: 12px;"
        "}"
        "QTreeWidget#metaTree::item { padding: 2px 0; }"
        "QTreeWidget#metaTree::item:selected { background: #2F65C5; color: #FFFFFF; }"
        "QTreeWidget#metaTree QHeaderView::section {"
        "  background: %36; color: %37; border: none; padding: 4px 6px; font-size: 12px;"
        "}"
        "QListWidget#favList {"
        "  background: %14; color: %1; border: none; font-size: 12px;"
        "}"
        "QListWidget#favList::item { padding: 3px 4px; }"
        "QListWidget#favList::item:selected { background: #2F65C5; color: #FFFFFF; }"
        "QListWidget#favList::item:hover { background: %30; }"
        // 重命名/裁剪/删除提示
        "QToolButton#renameInsertBtn {"
        "  color: #4C9AF5; background: transparent; border: none; padding: 4px 8px;"
        "}"
        "QToolButton#renameInsertBtn:hover"
        "{ color: #6FB1FF; text-decoration: underline; }"
        "QLabel#cropView { background: %38; }"
        "QLabel#cropInfo { color: %39; font-size: 12px; padding: 2px 6px; }"
        "QLabel#deleteToast {"
        "  background: %31; color: %2; font-size: 12px; font-weight: 600;"
        "  padding: 8px 14px; border-radius: 6px; border: 1px solid rgba(0,0,0,70);"
        "}"
    )
        .arg(C_TEXT)
        .arg(C_WIN_BG)
        .arg(C_TOOLBAR)
        .arg(C_SEPARATOR)
        .arg(C_ACCENT)
        .arg(C_SB_TRACK)
        .arg(C_SB_HANDLE)
        .arg(C_SB_HANDLE_H)
        .arg(C_SB_BUTTON)
        .arg(C_SB_BUTTON_H)
        .arg(C_SB_ARROW)
        .arg(C_CARD_BORDER)
        .arg(C_CONTENT)
        .arg(C_SIDEBAR)
        .arg(C_PREVIEW_BG)
        .arg(C_CARD_HOVER)
        .arg(C_SEPARATOR)      // %17:消息框按钮悬停(#215 起 C_PANE_HDR=#191919 不再作 hover,换描边灰=比按钮底亮一档)
        .arg(C_ACCENT_DOWN)    // %18:默认(确定)按钮悬停/按下,比 C_ACCENT 暗一档
        .arg(C_MENUBAR)        // %19:菜单栏底(#89 收敛自 mainwindow_menus 内联)
        .arg(C_PANE_HDR)       // %20:面板标题条底(#89 收敛自 createPaneHeader 内联)
        .arg(C_STATUSBAR)      // %21:状态栏底(#89 收敛自 createStatusbar 内联)
        .arg(C_TEXT_HIDDEN)    // %22:标签关闭钮常态字色(#89 收敛自 installTabCloseButton 内联)
        .arg(Theme::T("#4A4A56", "#9A9AA4"))  // %23:格式筛选框悬停描边(原内联局部双档值)
        .arg(Theme::T("#2A2A2E", "#C9C9D1"))  // %24:工具条竖分隔线(原内联局部双档值)
        .arg(C_TEXT_SUB)       // %25:查找条计数文字(#89 收敛自 filegrid_find 内联)
        .arg(C_TEXT_DIM)       // %26:占位/波形/RAW说明/搜索禁用字(#89 收敛自 previewpanel 等内联)
        .arg(C_CARD_BG)        // %27:RAW 按钮禁用底/组框卡底(#89 收敛自 previewpanel/settings 内联)
        .arg(C_TEXT_FAINT)     // %28:状态弱文字/禁用字/命中计数(#89 收敛自多处内联)
        .arg(C_TEXT_SOFT)      // %29:设置页组框标题(#89 收敛自 settings_dialog group 内联)
        .arg(C_TREE_HOVER)     // %30:收藏夹列表悬停行(#89 收敛自 favoritespanel 内联)
        .arg(C_SELECT_YELLOW)  // %31:删除提示琥珀底(#89 收敛自 shelldelete toast 内联)
        .arg(Theme::T("#D0D0D0", "#44444C"))  // %32:维护页统计行字色(原内联局部双档值)
        .arg(Theme::T("#B8B8C0", "#77777F"))  // %33:快捷键页鼠标说明字色(同上)
        .arg(Theme::T("#2A2A31", "#D9D9E0"))  // %34:信息面板直方图条下边线(原 infopanel 内联)
        .arg(Theme::T("#DCDCE2", "#1F1F26"))  // %35:元数据树行字色(同上)
        .arg(Theme::T("#232329", "#ECECEF"))  // %36:元数据树表头底(同上)
        .arg(Theme::T("#C8C8CE", "#44444C"))  // %37:元数据树表头字色(同上)
        .arg(Theme::T("#141418", "#E9E9ED"))  // %38:裁剪画布底(原 cropdialog 内联)
        .arg(Theme::T("#C8C8CE", "#44444C"))  // %39:裁剪信息条字色(同上)
        .arg(Theme::T("#0A0A0C", "#FFFFFF")); // %40:视频区底(浅色=白,#1)
}

} // namespace Theme
